// ═══════════════════════════════
// POKEMON DATA
// ═══════════════════════════════
const POKEMON=[
  {n:1,name:'Bulbasaur',types:['Grass','Poison']},{n:2,name:'Ivysaur',types:['Grass','Poison']},{n:3,name:'Venusaur',types:['Grass','Poison']},
  {n:4,name:'Charmander',types:['Fire']},{n:5,name:'Charmeleon',types:['Fire']},{n:6,name:'Charizard',types:['Fire','Flying']},
  {n:7,name:'Squirtle',types:['Water']},{n:8,name:'Wartortle',types:['Water']},{n:9,name:'Blastoise',types:['Water']},
  {n:10,name:'Caterpie',types:['Bug']},{n:11,name:'Metapod',types:['Bug']},{n:12,name:'Butterfree',types:['Bug','Flying']},
  {n:13,name:'Weedle',types:['Bug','Poison']},{n:14,name:'Kakuna',types:['Bug','Poison']},{n:15,name:'Beedrill',types:['Bug','Poison']},
  {n:16,name:'Pidgey',types:['Normal','Flying']},{n:17,name:'Pidgeotto',types:['Normal','Flying']},{n:18,name:'Pidgeot',types:['Normal','Flying']},
  {n:19,name:'Rattata',types:['Normal']},{n:20,name:'Raticate',types:['Normal']},{n:21,name:'Spearow',types:['Normal','Flying']},{n:22,name:'Fearow',types:['Normal','Flying']},
  {n:23,name:'Ekans',types:['Poison']},{n:24,name:'Arbok',types:['Poison']},{n:25,name:'Pikachu',types:['Electric']},{n:26,name:'Raichu',types:['Electric']},
  {n:27,name:'Sandshrew',types:['Ground']},{n:28,name:'Sandslash',types:['Ground']},
  {n:29,name:'Nidoran♀',types:['Poison']},{n:30,name:'Nidorina',types:['Poison']},{n:31,name:'Nidoqueen',types:['Poison','Ground']},
  {n:32,name:'Nidoran♂',types:['Poison']},{n:33,name:'Nidorino',types:['Poison']},{n:34,name:'Nidoking',types:['Poison','Ground']},
  {n:35,name:'Clefairy',types:['Normal']},{n:36,name:'Clefable',types:['Normal']},{n:37,name:'Vulpix',types:['Fire']},{n:38,name:'Ninetales',types:['Fire']},
  {n:39,name:'Jigglypuff',types:['Normal']},{n:40,name:'Wigglytuff',types:['Normal']},
  {n:41,name:'Zubat',types:['Poison','Flying']},{n:42,name:'Golbat',types:['Poison','Flying']},
  {n:43,name:'Oddish',types:['Grass','Poison']},{n:44,name:'Gloom',types:['Grass','Poison']},{n:45,name:'Vileplume',types:['Grass','Poison']},
  {n:46,name:'Paras',types:['Bug','Grass']},{n:47,name:'Parasect',types:['Bug','Grass']},{n:48,name:'Venonat',types:['Bug','Poison']},{n:49,name:'Venomoth',types:['Bug','Poison']},
  {n:50,name:'Diglett',types:['Ground']},{n:51,name:'Dugtrio',types:['Ground']},{n:52,name:'Meowth',types:['Normal']},{n:53,name:'Persian',types:['Normal']},
  {n:54,name:'Psyduck',types:['Water']},{n:55,name:'Golduck',types:['Water']},{n:56,name:'Mankey',types:['Fighting']},{n:57,name:'Primeape',types:['Fighting']},
  {n:58,name:'Growlithe',types:['Fire']},{n:59,name:'Arcanine',types:['Fire']},
  {n:60,name:'Poliwag',types:['Water']},{n:61,name:'Poliwhirl',types:['Water']},{n:62,name:'Poliwrath',types:['Water','Fighting']},
  {n:63,name:'Abra',types:['Psychic']},{n:64,name:'Kadabra',types:['Psychic']},{n:65,name:'Alakazam',types:['Psychic']},
  {n:66,name:'Machop',types:['Fighting']},{n:67,name:'Machoke',types:['Fighting']},{n:68,name:'Machamp',types:['Fighting']},
  {n:69,name:'Bellsprout',types:['Grass','Poison']},{n:70,name:'Weepinbell',types:['Grass','Poison']},{n:71,name:'Victreebel',types:['Grass','Poison']},
  {n:72,name:'Tentacool',types:['Water','Poison']},{n:73,name:'Tentacruel',types:['Water','Poison']},
  {n:74,name:'Geodude',types:['Rock','Ground']},{n:75,name:'Graveler',types:['Rock','Ground']},{n:76,name:'Golem',types:['Rock','Ground']},
  {n:77,name:'Ponyta',types:['Fire']},{n:78,name:'Rapidash',types:['Fire']},
  {n:79,name:'Slowpoke',types:['Water','Psychic']},{n:80,name:'Slowbro',types:['Water','Psychic']},
  {n:81,name:'Magnemite',types:['Electric','Steel']},{n:82,name:'Magneton',types:['Electric','Steel']},
  {n:83,name:"Farfetch'd",types:['Normal','Flying']},{n:84,name:'Doduo',types:['Normal','Flying']},{n:85,name:'Dodrio',types:['Normal','Flying']},
  {n:86,name:'Seel',types:['Water']},{n:87,name:'Dewgong',types:['Water','Ice']},{n:88,name:'Grimer',types:['Poison']},{n:89,name:'Muk',types:['Poison']},
  {n:90,name:'Shellder',types:['Water']},{n:91,name:'Cloyster',types:['Water','Ice']},
  {n:92,name:'Gastly',types:['Ghost','Poison']},{n:93,name:'Haunter',types:['Ghost','Poison']},{n:94,name:'Gengar',types:['Ghost','Poison']},
  {n:95,name:'Onix',types:['Rock','Ground']},{n:96,name:'Drowzee',types:['Psychic']},{n:97,name:'Hypno',types:['Psychic']},
  {n:98,name:'Krabby',types:['Water']},{n:99,name:'Kingler',types:['Water']},{n:100,name:'Voltorb',types:['Electric']},{n:101,name:'Electrode',types:['Electric']},
  {n:102,name:'Exeggcute',types:['Grass','Psychic']},{n:103,name:'Exeggutor',types:['Grass','Psychic']},
  {n:104,name:'Cubone',types:['Ground']},{n:105,name:'Marowak',types:['Ground']},
  {n:106,name:'Hitmonlee',types:['Fighting']},{n:107,name:'Hitmonchan',types:['Fighting']},{n:108,name:'Lickitung',types:['Normal']},
  {n:109,name:'Koffing',types:['Poison']},{n:110,name:'Weezing',types:['Poison']},
  {n:111,name:'Rhyhorn',types:['Ground','Rock']},{n:112,name:'Rhydon',types:['Ground','Rock']},
  {n:113,name:'Chansey',types:['Normal']},{n:114,name:'Tangela',types:['Grass']},{n:115,name:'Kangaskhan',types:['Normal']},
  {n:116,name:'Horsea',types:['Water']},{n:117,name:'Seadra',types:['Water']},{n:118,name:'Goldeen',types:['Water']},{n:119,name:'Seaking',types:['Water']},
  {n:120,name:'Staryu',types:['Water']},{n:121,name:'Starmie',types:['Water','Psychic']},{n:122,name:'Mr. Mime',types:['Psychic']},
  {n:123,name:'Scyther',types:['Bug','Flying']},{n:124,name:'Jynx',types:['Ice','Psychic']},
  {n:125,name:'Electabuzz',types:['Electric']},{n:126,name:'Magmar',types:['Fire']},{n:127,name:'Pinsir',types:['Bug']},{n:128,name:'Tauros',types:['Normal']},
  {n:129,name:'Magikarp',types:['Water']},{n:130,name:'Gyarados',types:['Water','Flying']},{n:131,name:'Lapras',types:['Water','Ice']},
  {n:132,name:'Ditto',types:['Normal']},{n:133,name:'Eevee',types:['Normal']},{n:134,name:'Vaporeon',types:['Water']},
  {n:135,name:'Jolteon',types:['Electric']},{n:136,name:'Flareon',types:['Fire']},{n:137,name:'Porygon',types:['Normal']},
  {n:138,name:'Omanyte',types:['Rock','Water']},{n:139,name:'Omastar',types:['Rock','Water']},
  {n:140,name:'Kabuto',types:['Rock','Water']},{n:141,name:'Kabutops',types:['Rock','Water']},
  {n:142,name:'Aerodactyl',types:['Rock','Flying']},{n:143,name:'Snorlax',types:['Normal']},
  {n:144,name:'Articuno',types:['Ice','Flying']},{n:145,name:'Zapdos',types:['Electric','Flying']},{n:146,name:'Moltres',types:['Fire','Flying']},
  {n:147,name:'Dratini',types:['Dragon']},{n:148,name:'Dragonair',types:['Dragon']},{n:149,name:'Dragonite',types:['Dragon','Flying']},
  {n:150,name:'Mewtwo',types:['Psychic']},{n:151,name:'Mew',types:['Psychic']}
];

// ═══════════════════════════════
// OBTAIN DATA
// HOW[n] = array of strings describing how to get it in FRLG
// DO NOT regenerate from PokeAPI — hand-curated for FRLG accuracy
// ═══════════════════════════════
const HOW={
  1:['Starter from Prof. Oak (FireRed)'],2:['Evolve Bulbasaur Lv.16'],3:['Evolve Ivysaur Lv.32'],
  4:['Starter from Prof. Oak'],5:['Evolve Charmander Lv.16'],6:['Evolve Charmeleon Lv.36'],
  7:['Starter from Prof. Oak (LeafGreen)'],8:['Evolve Squirtle Lv.16'],9:['Evolve Wartortle Lv.36'],
  10:['Grass: Route 2, Viridian Forest'],11:['Grass: Route 2, Viridian Forest'],12:['Evolve Caterpie Lv.10'],
  13:['Grass: Route 2, Viridian Forest'],14:['Grass: Route 2, Viridian Forest'],15:['Evolve Kakuna Lv.10'],
  16:['Grass: Route 1, 2, 3, 5, 6, 7, 8, 12, 13, 14, 15'],17:['Evolve Pidgey Lv.18'],18:['Evolve Pidgeotto Lv.36'],
  19:['Grass: Route 1, 2, 9, 16, 17, 18, 22'],20:['Evolve Rattata Lv.20'],
  21:['Grass: Route 3, 4, 9, 11, 16, 17, 18, 22, 23'],22:['Evolve Spearow Lv.20'],
  23:['Grass: Route 4, 9, 11, 23 (FireRed)'],24:['Evolve Ekans Lv.22'],
  25:['Grass: Viridian Forest (rare)'],26:['Evolve Pikachu (Thunder Stone)'],
  27:['Grass: Route 4, 9, 11, 23 (LeafGreen)'],28:['Evolve Sandshrew Lv.22'],
  29:['Grass: Route 22'],30:['Evolve Nidoran♀ Lv.16'],31:['Evolve Nidorina (Moon Stone)'],
  32:['Grass: Route 22'],33:['Evolve Nidoran♂ Lv.16'],34:['Evolve Nidorino (Moon Stone)'],
  35:['Grass: Mt. Moon'],36:['Evolve Clefairy (Moon Stone)'],
  37:['Grass: Route 7, 8 (LeafGreen)'],38:['Evolve Vulpix (Fire Stone)'],
  39:['Grass: Route 3'],40:['Evolve Jigglypuff (Moon Stone)'],
  41:['Grass: Mt. Moon, Rock Tunnel, Seafoam Islands, Victory Road'],42:['Evolve Zubat Lv.22'],
  43:['Grass: Route 5, 6, 7, 8 (FireRed)'],44:['Evolve Oddish Lv.21'],45:['Evolve Gloom (Leaf Stone)'],
  46:['Grass: Mt. Moon, Safari Zone Zone 1'],47:['Evolve Paras Lv.24'],
  48:['Grass: Route 12, 13, 14, 15 (FR), Safari Zone'],49:['Evolve Venonat Lv.31'],
  50:["Grass: Diglett's Cave"],51:["Evolve Diglett Lv.26"],
  52:['Grass: Route 5, 6, 7, 8 (LG)'],53:['Evolve Meowth Lv.28'],
  54:['Grass: Route 25 (rod), Cerulean Cave (surf)'],55:['Evolve Psyduck Lv.33'],
  56:['Grass: Route 3, 4 (FireRed)'],57:['Evolve Mankey Lv.28'],
  58:['Grass: Route 7, 8 (FireRed)'],59:['Evolve Growlithe (Fire Stone)'],
  60:['Grass: Route 10 (rod)'],61:['Evolve Poliwag Lv.25'],62:['Evolve Poliwhirl (Water Stone)'],
  63:['Grass: Route 24, 25'],64:['Evolve Abra Lv.16'],65:['Trade Kadabra'],
  66:['Grass: Rock Tunnel, Victory Road'],67:['Evolve Machop Lv.28'],68:['Trade Machoke'],
  69:['Grass: Route 5, 6, 7, 8 (LeafGreen)'],70:['Evolve Bellsprout Lv.21'],71:['Evolve Weepinbell (Leaf Stone)'],
  72:['Surf: most water routes'],73:['Evolve Tentacool Lv.30'],
  74:['Grass/Cave: Mt. Moon, Rock Tunnel, Victory Road'],75:['Evolve Geodude Lv.25'],76:['Trade Graveler'],
  77:['Grass: Route 17 (FireRed)'],78:['Evolve Ponyta Lv.40'],
  79:['Grass: Safari Zone (rod)'],80:['Evolve Slowpoke Lv.37'],
  81:['Grass: Route 10, Power Plant'],82:['Evolve Magnemite Lv.30'],
  83:['Gift in Vermilion City'],84:['Grass: Route 16, 17, 18'],85:['Evolve Doduo Lv.31'],
  86:['Grass: Seafoam Islands'],87:['Evolve Seel Lv.34'],
  88:['Grass: Pokémon Mansion'],89:['Evolve Grimer Lv.38'],
  90:['Grass: Water routes (rod)'],91:['Evolve Shellder (Water Stone)'],
  92:['Grass: Pokémon Tower, Lavender Town'],93:['Evolve Gastly Lv.25'],94:['Trade Haunter'],
  95:['Grass: Rock Tunnel, Victory Road'],96:['Grass: Route 11'],97:['Evolve Drowzee Lv.26'],
  98:['Grass: Seafoam Islands (rod)'],99:['Evolve Krabby Lv.28'],
  100:['Grass: Power Plant, Route 10'],101:['Evolve Voltorb Lv.30'],
  102:['Grass: Safari Zone Zone 2'],103:['Evolve Exeggcute (Leaf Stone)'],
  104:['Grass: Safari Zone Zone 1'],105:['Evolve Cubone Lv.28'],
  106:['Gift from Karate King (Fuchsia Gym)'],107:['Gift from Karate King (Fuchsia Gym)'],
  108:['Trade Slowbro (in-game trade)'],
  109:['Grass: Pokémon Mansion'],110:['Evolve Koffing Lv.35'],
  111:['Grass: Safari Zone Zone 1'],112:['Evolve Rhyhorn Lv.42'],
  113:['Grass: Safari Zone Zone 3, Cerulean Cave'],114:['Grass: Safari Zone Zone 3, Route 21'],
  115:['Grass: Safari Zone Zone 2'],
  116:['Grass: Seafoam Islands (surf), Route 19/20/21 (rod)'],117:['Evolve Horsea Lv.32'],
  118:['Grass: most water routes (rod)'],119:['Evolve Goldeen Lv.33'],
  120:['Grass: Seafoam Islands, water routes (rod)'],121:['Evolve Staryu (Water Stone)'],
  122:['Grass: Route 21 (LG)'],
  123:['Grass: Safari Zone Zone 2 (FireRed)'],124:['Grass: Seafoam Islands (LG)'],
  125:['Grass: Power Plant (FireRed)'],126:['Grass: Pokémon Mansion (FireRed)'],
  127:['Grass: Safari Zone Zone 2 (LeafGreen)'],128:['Grass: Safari Zone Zone 2'],
  129:['Fishing: most water routes (Old Rod)'],130:['Evolve Magikarp Lv.20'],
  131:['Gift on Silph Co. (from Silph employee)'],
  132:['Grass: Pokémon Mansion, Cerulean Cave, Routes 13-15'],
  133:['Gift from Bill in Celadon City'],134:['Evolve Eevee (Water Stone)'],
  135:['Evolve Eevee (Thunder Stone)'],136:['Evolve Eevee (Fire Stone)'],
  137:['Game Corner (9999 coins)'],
  138:['Fossil: Dome Fossil → revive in Cinnabar Lab'],139:['Evolve Omanyte Lv.40'],
  140:['Fossil: Helix Fossil → revive in Cinnabar Lab'],141:['Evolve Kabuto Lv.40'],
  142:['Fossil: Old Amber → revive in Cinnabar Lab'],
  143:['Sleeping on Routes 12 & 16 (use Poké Flute)'],
  144:['One-time: Seafoam Islands B4F'],145:['One-time: Power Plant'],146:['One-time: Mt. Ember (Sevii Islands)'],
  147:['Grass: Safari Zone Zone 4 (rare)'],148:['Evolve Dratini Lv.30'],149:['Evolve Dragonair Lv.55'],
  150:['One-time: Cerulean Cave B1F'],151:['Event only (Mew glitch or event)'],
};
function getObtain(n){return HOW[n]||['Method unknown'];}
