// ═══════════════════════════════
// MOVES
// ═══════════════════════════════
const ALL_MOVES=[
  {name:'Absorb',type:'Grass',cat:'spe'},{name:'Acid',type:'Poison',cat:'phy'},{name:'Acid Armor',type:'Poison',cat:'sta'},
  {name:'Aerial Ace',type:'Flying',cat:'phy'},{name:'Aeroblast',type:'Flying',cat:'phy'},{name:'Agility',type:'Psychic',cat:'sta'},
  {name:'Air Cutter',type:'Flying',cat:'phy'},{name:'Amnesia',type:'Psychic',cat:'sta'},{name:'Ancient Power',type:'Rock',cat:'phy'},
  {name:'Arm Thrust',type:'Fighting',cat:'phy'},{name:'Aromatherapy',type:'Grass',cat:'sta'},{name:'Assist',type:'Normal',cat:'sta'},
  {name:'Astonish',type:'Ghost',cat:'phy'},{name:'Attract',type:'Normal',cat:'sta'},{name:'Aurora Beam',type:'Ice',cat:'spe'},
  {name:'Barrage',type:'Normal',cat:'phy'},{name:'Barrier',type:'Psychic',cat:'sta'},{name:'Baton Pass',type:'Normal',cat:'sta'},
  {name:'Beat Up',type:'Dark',cat:'spe'},{name:'Belly Drum',type:'Normal',cat:'sta'},{name:'Bide',type:'Normal',cat:'phy'},
  {name:'Bind',type:'Normal',cat:'phy'},{name:'Bite',type:'Dark',cat:'spe'},{name:'Blast Burn',type:'Fire',cat:'spe'},
  {name:'Blaze Kick',type:'Fire',cat:'spe'},{name:'Blizzard',type:'Ice',cat:'spe'},{name:'Block',type:'Normal',cat:'sta'},
  {name:'Body Slam',type:'Normal',cat:'phy'},{name:'Bone Club',type:'Ground',cat:'phy'},{name:'Bone Rush',type:'Ground',cat:'phy'},
  {name:'Bonemerang',type:'Ground',cat:'phy'},{name:'Bounce',type:'Flying',cat:'phy'},{name:'Brick Break',type:'Fighting',cat:'phy'},
  {name:'Bubble',type:'Water',cat:'spe'},{name:'Bubble Beam',type:'Water',cat:'spe'},{name:'Bulk Up',type:'Fighting',cat:'sta'},
  {name:'Bullet Seed',type:'Grass',cat:'spe'},{name:'Calm Mind',type:'Psychic',cat:'sta'},{name:'Camouflage',type:'Normal',cat:'sta'},
  {name:'Charge',type:'Electric',cat:'sta'},{name:'Charm',type:'Normal',cat:'sta'},{name:'Clamp',type:'Water',cat:'spe'},
  {name:'Comet Punch',type:'Normal',cat:'phy'},{name:'Confuse Ray',type:'Ghost',cat:'sta'},{name:'Confusion',type:'Psychic',cat:'spe'},
  {name:'Constrict',type:'Normal',cat:'phy'},{name:'Conversion',type:'Normal',cat:'sta'},{name:'Conversion 2',type:'Normal',cat:'sta'},
  {name:'Cosmic Power',type:'Psychic',cat:'sta'},{name:'Cotton Spore',type:'Grass',cat:'sta'},{name:'Counter',type:'Fighting',cat:'phy'},
  {name:'Covet',type:'Normal',cat:'phy'},{name:'Crabhammer',type:'Water',cat:'spe'},{name:'Cross Chop',type:'Fighting',cat:'phy'},
  {name:'Crunch',type:'Dark',cat:'spe'},{name:'Crush Claw',type:'Normal',cat:'phy'},{name:'Curse',type:'???',cat:'sta'},
  {name:'Cut',type:'Normal',cat:'phy'},{name:'Defense Curl',type:'Normal',cat:'sta'},{name:'Destiny Bond',type:'Ghost',cat:'sta'},
  {name:'Detect',type:'Fighting',cat:'sta'},{name:'Dig',type:'Ground',cat:'phy'},{name:'Disable',type:'Normal',cat:'sta'},
  {name:'Dive',type:'Water',cat:'spe'},{name:'Dizzy Punch',type:'Normal',cat:'phy'},{name:'Doom Desire',type:'Steel',cat:'phy'},
  {name:'Double-Edge',type:'Normal',cat:'phy'},{name:'Double Kick',type:'Fighting',cat:'phy'},{name:'Double Slap',type:'Normal',cat:'phy'},
  {name:'Double Team',type:'Normal',cat:'sta'},{name:'Dragon Breath',type:'Dragon',cat:'spe'},{name:'Dragon Claw',type:'Dragon',cat:'spe'},
  {name:'Dragon Dance',type:'Dragon',cat:'sta'},{name:'Dragon Rage',type:'Dragon',cat:'spe'},{name:'Dream Eater',type:'Psychic',cat:'spe'},
  {name:'Drill Peck',type:'Flying',cat:'phy'},{name:'Dynamic Punch',type:'Fighting',cat:'phy'},{name:'Earthquake',type:'Ground',cat:'phy'},
  {name:'Egg Bomb',type:'Normal',cat:'phy'},{name:'Ember',type:'Fire',cat:'spe'},{name:'Encore',type:'Normal',cat:'sta'},
  {name:'Endeavor',type:'Normal',cat:'phy'},{name:'Endure',type:'Normal',cat:'sta'},{name:'Eruption',type:'Fire',cat:'spe'},
  {name:'Explosion',type:'Normal',cat:'phy'},{name:'Extrasensory',type:'Psychic',cat:'spe'},{name:'Extreme Speed',type:'Normal',cat:'phy'},
  {name:'Facade',type:'Normal',cat:'phy'},{name:'Faint Attack',type:'Dark',cat:'spe'},{name:'Fake Out',type:'Normal',cat:'phy'},
  {name:'Fake Tears',type:'Dark',cat:'sta'},{name:'False Swipe',type:'Normal',cat:'phy'},{name:'Feather Dance',type:'Flying',cat:'sta'},
  {name:'Fire Blast',type:'Fire',cat:'spe'},{name:'Fire Punch',type:'Fire',cat:'spe'},{name:'Fire Spin',type:'Fire',cat:'spe'},
  {name:'Fissure',type:'Ground',cat:'phy'},{name:'Flail',type:'Normal',cat:'phy'},{name:'Flame Wheel',type:'Fire',cat:'spe'},
  {name:'Flamethrower',type:'Fire',cat:'spe'},{name:'Flash',type:'Normal',cat:'sta'},{name:'Flatter',type:'Dark',cat:'sta'},
  {name:'Fly',type:'Flying',cat:'phy'},{name:'Focus Energy',type:'Normal',cat:'sta'},{name:'Focus Punch',type:'Fighting',cat:'phy'},
  {name:'Follow Me',type:'Normal',cat:'sta'},{name:'Foresight',type:'Normal',cat:'sta'},{name:'Frenzy Plant',type:'Grass',cat:'spe'},
  {name:'Frustration',type:'Normal',cat:'phy'},{name:'Fury Attack',type:'Normal',cat:'phy'},{name:'Fury Cutter',type:'Bug',cat:'phy'},
  {name:'Fury Swipes',type:'Normal',cat:'phy'},{name:'Future Sight',type:'Psychic',cat:'spe'},{name:'Giga Drain',type:'Grass',cat:'spe'},
  {name:'Glare',type:'Normal',cat:'sta'},{name:'Grass Whistle',type:'Grass',cat:'sta'},{name:'Growl',type:'Normal',cat:'sta'},
  {name:'Growth',type:'Normal',cat:'sta'},{name:'Grudge',type:'Ghost',cat:'sta'},{name:'Guillotine',type:'Normal',cat:'phy'},
  {name:'Gust',type:'Flying',cat:'phy'},{name:'Hail',type:'Ice',cat:'sta'},{name:'Harden',type:'Normal',cat:'sta'},
  {name:'Haze',type:'Ice',cat:'sta'},{name:'Headbutt',type:'Normal',cat:'phy'},{name:'Heal Bell',type:'Normal',cat:'sta'},
  {name:'Heat Wave',type:'Fire',cat:'spe'},{name:'Helping Hand',type:'Normal',cat:'sta'},{name:'Hidden Power',type:'Normal',cat:'spe'},
  {name:'High Jump Kick',type:'Fighting',cat:'phy'},
  {name:'Horn Attack',type:'Normal',cat:'phy'},{name:'Horn Drill',type:'Normal',cat:'phy'},{name:'Howl',type:'Normal',cat:'sta'},
  {name:'Hydro Cannon',type:'Water',cat:'spe'},{name:'Hydro Pump',type:'Water',cat:'spe'},{name:'Hyper Beam',type:'Normal',cat:'phy'},
  {name:'Hyper Fang',type:'Normal',cat:'phy'},{name:'Hyper Voice',type:'Normal',cat:'phy'},{name:'Hypnosis',type:'Psychic',cat:'sta'},
  {name:'Ice Ball',type:'Ice',cat:'spe'},{name:'Ice Beam',type:'Ice',cat:'spe'},{name:'Ice Punch',type:'Ice',cat:'spe'},
  {name:'Icicle Spear',type:'Ice',cat:'spe'},{name:'Icy Wind',type:'Ice',cat:'spe'},{name:'Imprison',type:'Psychic',cat:'sta'},
  {name:'Ingrain',type:'Grass',cat:'sta'},{name:'Iron Defense',type:'Steel',cat:'sta'},{name:'Iron Tail',type:'Steel',cat:'phy'},
  {name:'Jump Kick',type:'Fighting',cat:'phy'},{name:'Karate Chop',type:'Fighting',cat:'phy'},{name:'Kinesis',type:'Psychic',cat:'sta'},
  {name:'Knock Off',type:'Dark',cat:'spe'},{name:'Leaf Blade',type:'Grass',cat:'spe'},{name:'Leech Life',type:'Bug',cat:'phy'},
  {name:'Leech Seed',type:'Grass',cat:'sta'},{name:'Leer',type:'Normal',cat:'sta'},{name:'Lick',type:'Ghost',cat:'phy'},
  {name:'Light Screen',type:'Psychic',cat:'sta'},{name:'Lock-On',type:'Normal',cat:'sta'},{name:'Lovely Kiss',type:'Normal',cat:'sta'},
  {name:'Low Kick',type:'Fighting',cat:'phy'},{name:'Luster Purge',type:'Psychic',cat:'spe'},{name:'Mach Punch',type:'Fighting',cat:'phy'},
  {name:'Magic Coat',type:'Psychic',cat:'sta'},{name:'Magical Leaf',type:'Grass',cat:'spe'},{name:'Magnitude',type:'Ground',cat:'phy'},
  {name:'Mean Look',type:'Normal',cat:'sta'},{name:'Meditate',type:'Psychic',cat:'sta'},{name:'Mega Drain',type:'Grass',cat:'spe'},
  {name:'Mega Kick',type:'Normal',cat:'phy'},{name:'Mega Punch',type:'Normal',cat:'phy'},{name:'Megahorn',type:'Bug',cat:'phy'},
  {name:'Memento',type:'Dark',cat:'sta'},{name:'Metal Claw',type:'Steel',cat:'phy'},{name:'Metal Sound',type:'Steel',cat:'sta'},
  {name:'Meteor Mash',type:'Steel',cat:'phy'},{name:'Metronome',type:'Normal',cat:'sta'},{name:'Milk Drink',type:'Normal',cat:'sta'},
  {name:'Mimic',type:'Normal',cat:'sta'},{name:'Mind Reader',type:'Normal',cat:'sta'},{name:'Minimize',type:'Normal',cat:'sta'},
  {name:'Mirror Coat',type:'Psychic',cat:'spe'},{name:'Mirror Move',type:'Flying',cat:'sta'},{name:'Mist',type:'Ice',cat:'sta'},
  {name:'Mist Ball',type:'Psychic',cat:'spe'},{name:'Moonlight',type:'Normal',cat:'sta'},{name:'Morning Sun',type:'Normal',cat:'sta'},
  {name:'Mud-Slap',type:'Ground',cat:'phy'},{name:'Mud Shot',type:'Ground',cat:'phy'},{name:'Mud Sport',type:'Ground',cat:'sta'},
  {name:'Muddy Water',type:'Water',cat:'spe'},{name:'Nature Power',type:'Normal',cat:'sta'},{name:'Needle Arm',type:'Bug',cat:'phy'},
  {name:'Night Shade',type:'Ghost',cat:'phy'},{name:'Nightmare',type:'Ghost',cat:'sta'},{name:'Octazooka',type:'Water',cat:'spe'},
  {name:'Odor Sleuth',type:'Normal',cat:'sta'},{name:'Outrage',type:'Dragon',cat:'spe'},{name:'Overheat',type:'Fire',cat:'spe'},
  {name:'Pain Split',type:'Normal',cat:'sta'},{name:'Pay Day',type:'Normal',cat:'phy'},{name:'Peck',type:'Flying',cat:'phy'},
  {name:'Perish Song',type:'Normal',cat:'sta'},{name:'Petal Dance',type:'Grass',cat:'spe'},{name:'Pin Missile',type:'Bug',cat:'phy'},
  {name:'Poison Fang',type:'Poison',cat:'phy'},{name:'Poison Gas',type:'Poison',cat:'sta'},{name:'Poison Powder',type:'Poison',cat:'sta'},
  {name:'Poison Sting',type:'Poison',cat:'phy'},{name:'Poison Tail',type:'Poison',cat:'phy'},{name:'Pound',type:'Normal',cat:'phy'},
  {name:'Powder Snow',type:'Ice',cat:'spe'},{name:'Present',type:'Normal',cat:'phy'},{name:'Protect',type:'Normal',cat:'sta'},
  {name:'Psybeam',type:'Psychic',cat:'spe'},{name:'Psych Up',type:'Normal',cat:'sta'},{name:'Psychic',type:'Psychic',cat:'spe'},{name:'Psycho Boost',type:'Psychic',cat:'spe'},
  {name:'Psywave',type:'Psychic',cat:'spe'},{name:'Pursuit',type:'Dark',cat:'spe'},{name:'Quick Attack',type:'Normal',cat:'phy'},
  {name:'Rage',type:'Normal',cat:'phy'},{name:'Rain Dance',type:'Water',cat:'sta'},{name:'Rapid Spin',type:'Normal',cat:'phy'},
  {name:'Razor Leaf',type:'Grass',cat:'spe'},{name:'Razor Wind',type:'Normal',cat:'phy'},{name:'Recover',type:'Normal',cat:'sta'},
  {name:'Recycle',type:'Normal',cat:'sta'},{name:'Reflect',type:'Psychic',cat:'sta'},{name:'Refresh',type:'Normal',cat:'sta'},
  {name:'Rest',type:'Psychic',cat:'sta'},{name:'Return',type:'Normal',cat:'phy'},{name:'Revenge',type:'Fighting',cat:'phy'},
  {name:'Reversal',type:'Fighting',cat:'phy'},{name:'Roar',type:'Normal',cat:'sta'},{name:'Rock Blast',type:'Rock',cat:'phy'},
  {name:'Rock Slide',type:'Rock',cat:'phy'},{name:'Rock Smash',type:'Fighting',cat:'phy'},{name:'Rock Throw',type:'Rock',cat:'phy'},
  {name:'Rock Tomb',type:'Rock',cat:'phy'},{name:'Role Play',type:'Psychic',cat:'sta'},{name:'Rolling Kick',type:'Fighting',cat:'phy'},
  {name:'Rollout',type:'Rock',cat:'phy'},{name:'Sacred Fire',type:'Fire',cat:'spe'},{name:'Safeguard',type:'Normal',cat:'sta'},
  {name:'Sand-Attack',type:'Ground',cat:'sta'},{name:'Sand Tomb',type:'Ground',cat:'phy'},{name:'Sandstorm',type:'Rock',cat:'sta'},
  {name:'Scary Face',type:'Normal',cat:'sta'},{name:'Scratch',type:'Normal',cat:'phy'},{name:'Screech',type:'Normal',cat:'sta'},
  {name:'Secret Power',type:'Normal',cat:'phy'},{name:'Seismic Toss',type:'Fighting',cat:'phy'},{name:'Self-Destruct',type:'Normal',cat:'phy'},
  {name:'Shadow Ball',type:'Ghost',cat:'phy'},{name:'Shadow Punch',type:'Ghost',cat:'phy'},{name:'Sharpen',type:'Normal',cat:'sta'},
  {name:'Sheer Cold',type:'Ice',cat:'spe'},{name:'Shock Wave',type:'Electric',cat:'spe'},{name:'Signal Beam',type:'Bug',cat:'phy'},
  {name:'Silver Wind',type:'Bug',cat:'phy'},{name:'Sing',type:'Normal',cat:'sta'},{name:'Sketch',type:'Normal',cat:'sta'},
  {name:'Skill Swap',type:'Psychic',cat:'sta'},{name:'Skull Bash',type:'Normal',cat:'phy'},{name:'Sky Attack',type:'Flying',cat:'phy'},
  {name:'Sky Uppercut',type:'Fighting',cat:'phy'},{name:'Slack Off',type:'Normal',cat:'sta'},{name:'Slam',type:'Normal',cat:'phy'},
  {name:'Slash',type:'Normal',cat:'phy'},{name:'Sleep Powder',type:'Grass',cat:'sta'},{name:'Sleep Talk',type:'Normal',cat:'sta'},
  {name:'Sludge',type:'Poison',cat:'phy'},{name:'Sludge Bomb',type:'Poison',cat:'phy'},{name:'Smelling Salt',type:'Normal',cat:'phy'},
  {name:'Smog',type:'Poison',cat:'phy'},{name:'Smokescreen',type:'Normal',cat:'sta'},{name:'Snatch',type:'Dark',cat:'sta'},
  {name:'Snore',type:'Normal',cat:'phy'},{name:'Soft-Boiled',type:'Normal',cat:'sta'},{name:'Solar Beam',type:'Grass',cat:'spe'},
  {name:'Sonic Boom',type:'Normal',cat:'phy'},{name:'Spark',type:'Electric',cat:'spe'},{name:'Spider Web',type:'Bug',cat:'sta'},
  {name:'Spike Cannon',type:'Normal',cat:'phy'},{name:'Spikes',type:'Ground',cat:'sta'},{name:'Spit Up',type:'Normal',cat:'phy'},
  {name:'Spite',type:'Ghost',cat:'sta'},{name:'Splash',type:'Normal',cat:'sta'},{name:'Spore',type:'Grass',cat:'sta'},
  {name:'Steel Wing',type:'Steel',cat:'phy'},{name:'Stockpile',type:'Normal',cat:'sta'},{name:'Stomp',type:'Normal',cat:'phy'},
  {name:'Strength',type:'Normal',cat:'phy'},{name:'String Shot',type:'Bug',cat:'sta'},{name:'Struggle',type:'Normal',cat:'phy'},
  {name:'Stun Spore',type:'Grass',cat:'sta'},{name:'Submission',type:'Fighting',cat:'phy'},{name:'Substitute',type:'Normal',cat:'sta'},
  {name:'Sunny Day',type:'Fire',cat:'sta'},{name:'Super Fang',type:'Normal',cat:'phy'},{name:'Superpower',type:'Fighting',cat:'phy'},
  {name:'Supersonic',type:'Normal',cat:'sta'},{name:'Surf',type:'Water',cat:'spe'},{name:'Swagger',type:'Normal',cat:'sta'},
  {name:'Swallow',type:'Normal',cat:'sta'},{name:'Sweet Kiss',type:'Normal',cat:'sta'},{name:'Sweet Scent',type:'Normal',cat:'sta'},
  {name:'Swift',type:'Normal',cat:'phy'},{name:'Swords Dance',type:'Normal',cat:'sta'},{name:'Synthesis',type:'Grass',cat:'sta'},
  {name:'Tackle',type:'Normal',cat:'phy'},{name:'Tail Glow',type:'Bug',cat:'sta'},{name:'Tail Whip',type:'Normal',cat:'sta'},
  {name:'Take Down',type:'Normal',cat:'phy'},{name:'Taunt',type:'Dark',cat:'sta'},{name:'Teeter Dance',type:'Normal',cat:'sta'},
  {name:'Teleport',type:'Psychic',cat:'sta'},{name:'Thief',type:'Dark',cat:'spe'},{name:'Thrash',type:'Normal',cat:'phy'},
  {name:'Thunder',type:'Electric',cat:'spe'},{name:'Thunder Punch',type:'Fire',cat:'spe'},{name:'Thunder Shock',type:'Electric',cat:'spe'},
  {name:'Thunder Wave',type:'Electric',cat:'sta'},{name:'Thunderbolt',type:'Electric',cat:'spe'},{name:'Tickle',type:'Normal',cat:'sta'},
  {name:'Torment',type:'Dark',cat:'sta'},{name:'Toxic',type:'Poison',cat:'sta'},{name:'Transform',type:'Normal',cat:'sta'},
  {name:'Tri Attack',type:'Normal',cat:'phy'},{name:'Trick',type:'Psychic',cat:'sta'},{name:'Triple Kick',type:'Fighting',cat:'phy'},
  {name:'Twineedle',type:'Bug',cat:'phy'},{name:'Twister',type:'Dragon',cat:'spe'},{name:'Uproar',type:'Normal',cat:'phy'},
  {name:'Vice Grip',type:'Normal',cat:'phy'},{name:'Vine Whip',type:'Grass',cat:'spe'},{name:'Vital Throw',type:'Fighting',cat:'phy'},
  {name:'Volt Tackle',type:'Electric',cat:'spe'},{name:'Water Gun',type:'Water',cat:'spe'},{name:'Water Pulse',type:'Water',cat:'spe'},
  {name:'Water Sport',type:'Water',cat:'sta'},{name:'Water Spout',type:'Water',cat:'spe'},{name:'Waterfall',type:'Water',cat:'spe'},
  {name:'Weather Ball',type:'Normal',cat:'phy'},{name:'Whirlpool',type:'Water',cat:'spe'},{name:'Whirlwind',type:'Normal',cat:'sta'},
  {name:'Will-O-Wisp',type:'Fire',cat:'sta'},{name:'Wing Attack',type:'Flying',cat:'phy'},{name:'Wish',type:'Normal',cat:'sta'},
  {name:'Withdraw',type:'Water',cat:'sta'},{name:'Wrap',type:'Normal',cat:'phy'},{name:'Yawn',type:'Normal',cat:'sta'},
  {name:'Zap Cannon',type:'Electric',cat:'spe'},
];

// ═══════════════════════════════
// TMs & HMs — FRLG locations
// DO NOT alter — verified against FRLG via Serebii + Bulbapedia
// ═══════════════════════════════
const TM_HM=[
  {num:'TM01',move:'Focus Punch',type:'Fighting',cat:'phy',loc:'Silph Co. (Floor 5)'},
  {num:'TM02',move:'Dragon Claw',type:'Dragon',cat:'spe',loc:'Victory Road'},
  {num:'TM03',move:'Water Pulse',type:'Water',cat:'spe',loc:'Cerulean Gym — Misty reward'},
  {num:'TM04',move:'Calm Mind',type:'Psychic',cat:'sta',loc:'Saffron Gym — Sabrina reward'},
  {num:'TM05',move:'Roar',type:'Normal',cat:'sta',loc:'Route 4 / Celadon Dept. Store (₽1000)'},
  {num:'TM06',move:'Toxic',type:'Poison',cat:'sta',loc:'Fuchsia Gym — Koga reward'},
  {num:'TM07',move:'Hail',type:'Ice',cat:'sta',loc:'Victory Road'},
  {num:'TM08',move:'Bulk Up',type:'Fighting',cat:'sta',loc:'Silph Co. (Floor 7)'},
  {num:'TM09',move:'Bullet Seed',type:'Grass',cat:'spe',loc:'Mt. Moon (entrance)'},
  {num:'TM10',move:'Hidden Power',type:'Normal',cat:'spe',loc:'Pickup ability (5% chance)'},
  {num:'TM11',move:'Sunny Day',type:'Fire',cat:'sta',loc:'Safari Zone'},
  {num:'TM12',move:'Taunt',type:'Dark',cat:'sta',loc:'Team Rocket Hideout (B2)'},
  {num:'TM13',move:'Ice Beam',type:'Ice',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM14',move:'Blizzard',type:'Ice',cat:'spe',loc:'Pokémon Mansion'},
  {num:'TM15',move:'Hyper Beam',type:'Normal',cat:'phy',loc:'Celadon Dept. Store (₽7500)'},
  {num:'TM16',move:'Light Screen',type:'Psychic',cat:'sta',loc:'Celadon Dept. Store (roof, ₽3000)'},
  {num:'TM17',move:'Protect',type:'Normal',cat:'sta',loc:'Kanto Power Plant'},
  {num:'TM18',move:'Rain Dance',type:'Water',cat:'sta',loc:'Route 15'},
  {num:'TM19',move:'Giga Drain',type:'Grass',cat:'spe',loc:'Celadon Gym — Erika reward'},
  {num:'TM20',move:'Safeguard',type:'Normal',cat:'sta',loc:'Celadon Dept. Store (roof, ₽3000)'},
  {num:'TM21',move:'Frustration',type:'Normal',cat:'phy',loc:'Team Rocket Hideout (B3)'},
  {num:'TM22',move:'Solar Beam',type:'Grass',cat:'spe',loc:'Pokémon Mansion'},
  {num:'TM23',move:'Iron Tail',type:'Steel',cat:'phy',loc:'Celadon Game Corner (3500 coins)'},
  {num:'TM24',move:'Thunderbolt',type:'Electric',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM25',move:'Thunder',type:'Electric',cat:'spe',loc:'Kanto Power Plant'},
  {num:'TM26',move:'Earthquake',type:'Ground',cat:'phy',loc:'Viridian Gym — Giovanni reward'},
  {num:'TM27',move:'Return',type:'Normal',cat:'phy',loc:'Route 12'},
  {num:'TM28',move:'Dig',type:'Ground',cat:'phy',loc:'Cerulean City NPC / Celadon Dept. Store'},
  {num:'TM29',move:'Psychic',type:'Psychic',cat:'spe',loc:'Saffron City (Mr. Psychic\'s house) / Game Corner (3500 coins)'},
  {num:'TM30',move:'Shadow Ball',type:'Ghost',cat:'phy',loc:'Celadon Game Corner (4500 coins)'},
  {num:'TM31',move:'Brick Break',type:'Fighting',cat:'phy',loc:'S.S. Anne / Celadon Dept. Store'},
  {num:'TM32',move:'Double Team',type:'Normal',cat:'sta',loc:'Safari Zone'},
  {num:'TM33',move:'Reflect',type:'Psychic',cat:'sta',loc:'S.S. Anne (B1) / Celadon Dept. Store'},
  {num:'TM34',move:'Shock Wave',type:'Electric',cat:'spe',loc:'Vermilion Gym — Lt. Surge reward'},
  {num:'TM35',move:'Flamethrower',type:'Fire',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM36',move:'Sludge Bomb',type:'Poison',cat:'spe',loc:'Team Rocket HQ (Island 5)'},
  {num:'TM37',move:'Sandstorm',type:'Rock',cat:'sta',loc:'Victory Road'},
  {num:'TM38',move:'Fire Blast',type:'Fire',cat:'spe',loc:'Cinnabar Gym — Blaine reward / Silph Co. (Floor 7)'},
  {num:'TM39',move:'Rock Tomb',type:'Rock',cat:'phy',loc:'Pewter Gym — Brock reward / Silph Co. (Floor 4)'},
  {num:'TM40',move:'Aerial Ace',type:'Flying',cat:'phy',loc:'Route 9'},
  {num:'TM41',move:'Torment',type:'Dark',cat:'sta',loc:'Silph Co. (Floor 4)'},
  {num:'TM42',move:'Facade',type:'Normal',cat:'phy',loc:'Rock Altar (Island 6)'},
  {num:'TM43',move:'Secret Power',type:'Normal',cat:'phy',loc:'Route 24 / Celadon Dept. Store'},
  {num:'TM44',move:'Rest',type:'Psychic',cat:'sta',loc:'Route 9'},
  {num:'TM45',move:'Attract',type:'Normal',cat:'sta',loc:'Route 24 / Celadon Dept. Store'},
  {num:'TM46',move:'Thief',type:'Dark',cat:'phy',loc:'Mt. Moon (B2)'},
  {num:'TM47',move:'Steel Wing',type:'Steel',cat:'phy',loc:'Safari Zone'},
  {num:'TM48',move:'Skill Swap',type:'Psychic',cat:'sta',loc:'Route 12'},
  {num:'TM49',move:'Snatch',type:'Dark',cat:'sta',loc:'Team Rocket Hideout (B4)'},
  {num:'TM50',move:'Overheat',type:'Fire',cat:'spe',loc:'Victory Road'},
  {num:'HM01',move:'Cut',type:'Normal',cat:'phy',loc:'S.S. Anne — Captain gift'},
  {num:'HM02',move:'Fly',type:'Flying',cat:'phy',loc:'Route 16'},
  {num:'HM03',move:'Surf',type:'Water',cat:'spe',loc:'Safari Zone (Secret House)'},
  {num:'HM04',move:'Strength',type:'Normal',cat:'phy',loc:'Safari Zone Warden (return Gold Teeth)'},
  {num:'HM05',move:'Flash',type:'Normal',cat:'sta',loc:'Route 2 (Oak\'s Aide, after 10 Pokémon caught)'},
  {num:'HM06',move:'Rock Smash',type:'Fighting',cat:'phy',loc:'Island 1 (Ember Spa)'},
  {num:'HM07',move:'Waterfall',type:'Water',cat:'spe',loc:'Island 4 (Icefall Cave)'},
];

// Tag each entry with tmType ('tm' | 'hm') and derive buyable=true for repurchaseable
// Celadon Dept. Store / Game Corner TMs — avoids touching each row individually.
TM_HM.forEach(t => {
  t.tmType = t.num.startsWith('HM') ? 'hm' : 'tm';
  t.buyable = t.tmType === 'tm' && /Dept\. Store|Game Corner/.test(t.loc);
});

// ═══════════════════════════════
// MOVE DATA — Gen III (FRLG)
// [pow, acc, eff]
//   pow = base power (0 = status/no damage)
//   acc = accuracy % (0 = always hits or no accuracy check)
//   eff = secondary effect (optional)
// ═══════════════════════════════
const MOVE_DATA={
  'Absorb':[20,100,'drain'],'Acid':[40,100,'-1 spd 10%'],
  'Aerial Ace':[60,0],'Aeroblast':[100,95,'high crit'],
  'Air Cutter':[55,95,'high crit'],
  'Ancient Power':[60,100,'all +1 10%'],
  'Arm Thrust':[15,100],'Astonish':[30,100,'flinch 30%'],
  'Aurora Beam':[65,100,'-1 atk 10%'],
  'Barrage':[15,85],'Beat Up':[10,100],'Bind':[15,75,'traps'],
  'Bite':[60,100,'flinch 30%'],
  'Blast Burn':[150,90,'recharge'],'Blaze Kick':[85,90,'burn 10%'],
  'Blizzard':[120,70,'freeze 10%'],'Body Slam':[85,100,'para 30%'],
  'Bone Club':[65,85,'flinch 10%'],'Bone Rush':[25,90],'Bonemerang':[50,90],
  'Bounce':[85,85,'para 30%'],'Brick Break':[75,100],
  'Bubble':[20,100,'-1 spd 10%'],'Bubble Beam':[65,100,'-1 spd 10%'],
  'Bullet Seed':[10,100],'Clamp':[35,75,'traps'],'Comet Punch':[18,85],
  'Confusion':[50,100,'confuse 10%'],'Constrict':[10,100,'-1 spd 10%'],
  'Covet':[40,100],'Crabhammer':[90,85],
  'Cross Chop':[100,80,'high crit'],'Crunch':[80,100,'-1 spdef 20%'],
  'Crush Claw':[75,95,'-1 def 50%'],'Cut':[50,95],
  'Dig':[60,100],'Dive':[60,100],'Dizzy Punch':[70,100,'confuse 20%'],
  'Doom Desire':[120,85],'Double-Edge':[120,100,'recoil'],
  'Double Kick':[30,100],'Double Slap':[15,85],
  'Dragon Breath':[60,100,'para 30%'],'Dragon Claw':[80,100],
  'Dragon Rage':[0,100],'Dream Eater':[100,100,'drain'],
  'Drill Peck':[80,100],'Dynamic Punch':[100,50,'confuse 100%'],
  'Earthquake':[100,100],'Egg Bomb':[100,75],
  'Ember':[40,100,'burn 10%'],'Endeavor':[0,100],
  'Eruption':[150,100],'Explosion':[250,100],
  'Extrasensory':[80,100,'flinch 10%'],'Extreme Speed':[80,100],
  'Facade':[70,100],'Faint Attack':[60,0],
  'Fake Out':[40,100,'flinch 100%'],'False Swipe':[40,100],
  'Fire Blast':[120,85,'burn 10%'],'Fire Punch':[75,100,'burn 10%'],
  'Fire Spin':[15,70,'traps'],'Fissure':[0,30,'OHKO'],
  'Flame Wheel':[60,100,'burn 10%'],'Flamethrower':[95,100,'burn 10%'],
  'Fly':[70,95],'Focus Punch':[150,100],
  'Frenzy Plant':[150,90,'recharge'],
  'Fury Attack':[15,85],'Fury Cutter':[10,95],'Fury Swipes':[18,80],
  'Future Sight':[80,90],
  'Giga Drain':[60,100,'drain'],'Guillotine':[0,30,'OHKO'],
  'Gust':[40,100],'Headbutt':[70,100,'flinch 30%'],
  'Heat Wave':[100,90,'burn 10%'],'High Jump Kick':[85,90],
  'Horn Attack':[65,100],'Horn Drill':[0,30,'OHKO'],
  'Hydro Cannon':[150,90,'recharge'],'Hydro Pump':[120,80],
  'Hyper Beam':[150,90,'recharge'],'Hyper Fang':[80,90,'flinch 10%'],
  'Hyper Voice':[90,100],'Ice Ball':[30,90],
  'Ice Beam':[95,100,'freeze 10%'],'Ice Punch':[75,100,'freeze 10%'],
  'Icicle Spear':[10,100],'Icy Wind':[55,95,'-1 spd'],
  'Iron Tail':[100,75,'-1 def 30%'],
  'Jump Kick':[70,95],'Karate Chop':[50,100,'high crit'],
  'Knock Off':[20,100],'Leaf Blade':[70,100,'high crit'],
  'Leech Life':[20,100,'drain'],'Lick':[20,100,'para 30%'],
  'Low Kick':[0,100],'Luster Purge':[70,100,'-1 spdef 50%'],
  'Mach Punch':[40,100],'Magical Leaf':[60,0],
  'Magnitude':[0,100],'Mega Drain':[40,100,'drain'],
  'Mega Kick':[120,75],'Mega Punch':[80,85],'Megahorn':[120,85],
  'Metal Claw':[50,95,'+1 atk 10%'],'Meteor Mash':[100,85,'+1 atk 20%'],
  'Mist Ball':[70,100,'-1 spatk 50%'],
  'Mud Shot':[55,95,'-1 spd'],'Mud-Slap':[20,100,'-1 acc'],
  'Muddy Water':[95,85,'-1 acc 30%'],'Needle Arm':[60,100,'flinch 30%'],
  'Night Shade':[0,100],'Octazooka':[65,85,'-1 acc 50%'],
  'Outrage':[90,100,'confuse after'],'Overheat':[140,90,'-2 spatk'],
  'Pay Day':[40,100],'Peck':[35,100],
  'Petal Dance':[70,100,'confuse after'],
  'Pin Missile':[14,85],'Poison Fang':[50,100,'bad psn 30%'],
  'Poison Sting':[15,100,'psn 30%'],'Poison Tail':[50,100,'psn 10%'],
  'Pound':[40,100],'Powder Snow':[40,100,'freeze 10%'],
  'Psybeam':[65,100,'confuse 10%'],'Psychic':[90,100,'-1 spdef 10%'],
  'Psycho Boost':[140,90,'-2 spatk'],'Psywave':[0,80],
  'Pursuit':[40,100],'Quick Attack':[40,100],'Rage':[20,100],
  'Rapid Spin':[20,100],'Razor Leaf':[55,95,'high crit'],
  'Razor Wind':[80,100,'high crit'],'Revenge':[60,100],
  'Rock Blast':[25,80],'Rock Slide':[75,90,'flinch 30%'],
  'Rock Smash':[20,100,'-1 def 50%'],'Rock Throw':[50,90],
  'Rock Tomb':[50,80,'-1 spd'],'Rolling Kick':[60,85,'flinch 30%'],
  'Rollout':[30,90],'Sacred Fire':[100,95,'burn 50%'],
  'Sand Tomb':[15,70,'traps'],'Scratch':[40,100],
  'Secret Power':[70,100],'Seismic Toss':[0,100],
  'Self-Destruct':[200,100],'Shadow Ball':[80,100,'-1 spdef 20%'],
  'Shadow Punch':[60,0],'Sheer Cold':[0,30,'OHKO'],
  'Shock Wave':[60,0],'Signal Beam':[75,100,'confuse 10%'],
  'Silver Wind':[60,100,'all +1 10%'],'Sky Attack':[140,90,'flinch 30%'],
  'Sky Uppercut':[85,90],'Slam':[80,75],'Slash':[70,100,'high crit'],
  'Sludge':[65,100,'psn 30%'],'Sludge Bomb':[90,100,'psn 30%'],
  'Smog':[20,70,'psn 40%'],'Snore':[40,100,'flinch 30%'],
  'Solar Beam':[120,100],'Spark':[65,100,'para 30%'],
  'Spike Cannon':[20,100],'Steel Wing':[70,90,'+1 def 10%'],
  'Stomp':[65,100,'flinch 30%'],'Strength':[80,100],
  'Submission':[80,80,'recoil'],'Surf':[95,100],'Swift':[60,0],
  'Tackle':[35,95],'Take Down':[90,85,'recoil'],
  'Thief':[40,100],'Thrash':[90,100,'confuse after'],
  'Thunder':[120,70,'para 30%'],'Thunder Punch':[75,100,'para 10%'],
  'Thunder Shock':[40,100,'para 10%'],'Thunderbolt':[95,100,'para 10%'],
  'Tri Attack':[80,100,'burn/freeze/para 20%'],
  'Triple Kick':[10,90],'Twineedle':[25,100,'psn 20%'],
  'Twister':[40,100,'flinch 20%'],'Uproar':[50,100],
  'Vice Grip':[55,100],'Vine Whip':[35,100],'Vital Throw':[70,0],
  'Volt Tackle':[120,100,'recoil, para 10%'],
  'Water Gun':[40,100],'Water Pulse':[60,100,'confuse 20%'],
  'Water Spout':[150,100],'Waterfall':[80,100,'flinch 20%'],
  'Wing Attack':[60,100],'Wrap':[15,85,'traps'],'Zap Cannon':[100,50,'para 100%'],
  // Status moves
  'Attract':[0,100,'infatuates'],'Charm':[0,100,'-2 atk'],
  'Confuse Ray':[0,100,'confuses'],'Cotton Spore':[0,85,'-2 spd'],
  'Fake Tears':[0,100,'-2 spdef'],'Feather Dance':[0,100,'-2 atk'],
  'Flash':[0,70,'-1 acc'],'Glare':[0,75,'para'],
  'Grass Whistle':[0,55,'sleep'],'Growl':[0,100,'-1 atk'],
  'Hypnosis':[0,60,'sleep'],'Leech Seed':[0,90,'drains HP'],
  'Leer':[0,100,'-1 def'],'Lovely Kiss':[0,75,'sleep'],
  'Mean Look':[0,100,'traps'],'Metal Sound':[0,85,'-2 spdef'],
  'Poison Gas':[0,55,'poisons'],'Poison Powder':[0,75,'poisons'],
  'Sand-Attack':[0,100,'-1 acc'],'Scary Face':[0,90,'-2 spd'],
  'Screech':[0,85,'-2 def'],'Sing':[0,55,'sleep'],
  'Sleep Powder':[0,75,'sleep'],'Smokescreen':[0,100,'-1 acc'],
  'Spore':[0,100,'sleep'],'String Shot':[0,95,'-1 spd'],
  'Stun Spore':[0,75,'para'],'Supersonic':[0,55,'confuses'],
  'Sweet Kiss':[0,75,'confuses'],'Tail Whip':[0,100,'-1 def'],
  'Thunder Wave':[0,100,'para'],'Toxic':[0,85,'bad psn'],
  'Will-O-Wisp':[0,75,'burns'],'Yawn':[0,100,'sleep (next turn)'],
};
