// ═══════════════════════════════
// MOVES
// ═══════════════════════════════
const ALL_MOVES=[
  {name:'Absorb',type:'Grass',cat:'spe'},{name:'Acid',type:'Poison',cat:'spe'},{name:'Aerial Ace',type:'Flying',cat:'phy'},
  {name:'Agility',type:'Psychic',cat:'sta'},{name:'Ancient Power',type:'Rock',cat:'spe'},{name:'Aurora Beam',type:'Ice',cat:'spe'},
  {name:'Barrier',type:'Psychic',cat:'sta'},{name:'Baton Pass',type:'Normal',cat:'sta'},{name:'Beat Up',type:'Dark',cat:'phy'},
  {name:'Bite',type:'Dark',cat:'spe'},{name:'Blizzard',type:'Ice',cat:'spe'},{name:'Body Slam',type:'Normal',cat:'phy'},
  {name:'Bone Club',type:'Ground',cat:'phy'},{name:'Bone Rush',type:'Ground',cat:'phy'},{name:'Bonemerang',type:'Ground',cat:'phy'},
  {name:'Brick Break',type:'Fighting',cat:'phy'},{name:'Bug Bite',type:'Bug',cat:'phy'},{name:'Bullet Seed',type:'Grass',cat:'spe'},
  {name:'Calm Mind',type:'Psychic',cat:'sta'},{name:'Charge',type:'Electric',cat:'sta'},{name:'Confuse Ray',type:'Ghost',cat:'sta'},
  {name:'Confusion',type:'Psychic',cat:'spe'},{name:'Counter',type:'Fighting',cat:'phy'},{name:'Cross Chop',type:'Fighting',cat:'phy'},
  {name:'Crunch',type:'Dark',cat:'spe'},{name:'Cut',type:'Normal',cat:'phy'},{name:'Defense Curl',type:'Normal',cat:'sta'},
  {name:'Destiny Bond',type:'Ghost',cat:'sta'},{name:'Detect',type:'Fighting',cat:'sta'},{name:'Dig',type:'Ground',cat:'phy'},
  {name:'Double-Edge',type:'Normal',cat:'phy'},{name:'Double Team',type:'Normal',cat:'sta'},{name:'Dragon Breath',type:'Dragon',cat:'spe'},
  {name:'Dragon Claw',type:'Dragon',cat:'spe'},{name:'Dragon Dance',type:'Dragon',cat:'sta'},{name:'Dragon Rage',type:'Dragon',cat:'spe'},
  {name:'Drill Peck',type:'Flying',cat:'phy'},{name:'Dynamic Punch',type:'Fighting',cat:'phy'},{name:'Earthquake',type:'Ground',cat:'phy'},
  {name:'Ember',type:'Fire',cat:'spe'},{name:'Encore',type:'Normal',cat:'sta'},{name:'Extrasensory',type:'Psychic',cat:'spe'},
  {name:'Extreme Speed',type:'Normal',cat:'phy'},{name:'Facade',type:'Normal',cat:'phy'},{name:'Faint Attack',type:'Dark',cat:'phy'},
  {name:'Fire Blast',type:'Fire',cat:'spe'},{name:'Fire Spin',type:'Fire',cat:'spe'},{name:'Fissure',type:'Ground',cat:'phy'},
  {name:'Flamethrower',type:'Fire',cat:'spe'},{name:'Fly',type:'Flying',cat:'phy'},{name:'Focus Punch',type:'Fighting',cat:'phy'},
  {name:'Frustration',type:'Normal',cat:'phy'},{name:'Future Sight',type:'Psychic',cat:'spe'},{name:'Giga Drain',type:'Grass',cat:'spe'},
  {name:'Growl',type:'Normal',cat:'sta'},{name:'Gust',type:'Flying',cat:'spe'},{name:'Hail',type:'Ice',cat:'sta'},
  {name:'Headbutt',type:'Normal',cat:'phy'},{name:'Heat Wave',type:'Fire',cat:'spe'},{name:'Hyper Beam',type:'Normal',cat:'phy'},
  {name:'Ice Beam',type:'Ice',cat:'spe'},{name:'Ice Punch',type:'Ice',cat:'spe'},{name:'Icy Wind',type:'Ice',cat:'spe'},
  {name:'Iron Defense',type:'Steel',cat:'sta'},{name:'Iron Tail',type:'Steel',cat:'phy'},{name:'Karate Chop',type:'Fighting',cat:'phy'},
  {name:'Knock Off',type:'Dark',cat:'phy'},{name:'Leech Life',type:'Bug',cat:'phy'},{name:'Leech Seed',type:'Grass',cat:'sta'},
  {name:'Leer',type:'Normal',cat:'sta'},{name:'Lick',type:'Ghost',cat:'phy'},{name:'Light Screen',type:'Psychic',cat:'sta'},
  {name:'Low Kick',type:'Fighting',cat:'phy'},{name:'Mach Punch',type:'Fighting',cat:'phy'},{name:'Magical Leaf',type:'Grass',cat:'spe'},
  {name:'Magnitude',type:'Ground',cat:'phy'},{name:'Mega Drain',type:'Grass',cat:'spe'},{name:'Mega Kick',type:'Normal',cat:'phy'},
  {name:'Mega Punch',type:'Normal',cat:'phy'},{name:'Megahorn',type:'Bug',cat:'phy'},{name:'Metal Claw',type:'Steel',cat:'phy'},
  {name:'Metal Sound',type:'Steel',cat:'sta'},{name:'Meteor Mash',type:'Steel',cat:'phy'},{name:'Mirror Move',type:'Flying',cat:'sta'},
  {name:'Mud Shot',type:'Ground',cat:'spe'},{name:'Mud Slap',type:'Ground',cat:'spe'},{name:'Night Shade',type:'Ghost',cat:'spe'},
  {name:'Outrage',type:'Dragon',cat:'spe'},{name:'Overheat',type:'Fire',cat:'spe'},{name:'Peck',type:'Flying',cat:'phy'},
  {name:'Petal Dance',type:'Grass',cat:'spe'},{name:'Pin Missile',type:'Bug',cat:'phy'},{name:'Poison Gas',type:'Poison',cat:'sta'},
  {name:'Poison Powder',type:'Poison',cat:'sta'},{name:'Poison Sting',type:'Poison',cat:'phy'},{name:'Powder Snow',type:'Ice',cat:'spe'},
  {name:'Protect',type:'Normal',cat:'sta'},{name:'Psybeam',type:'Psychic',cat:'spe'},{name:'Psychic',type:'Psychic',cat:'spe'},
  {name:'Pursuit',type:'Dark',cat:'phy'},{name:'Quick Attack',type:'Normal',cat:'phy'},{name:'Rain Dance',type:'Water',cat:'sta'},
  {name:'Razor Leaf',type:'Grass',cat:'spe'},{name:'Reflect',type:'Psychic',cat:'sta'},{name:'Rest',type:'Psychic',cat:'sta'},
  {name:'Return',type:'Normal',cat:'phy'},{name:'Rock Blast',type:'Rock',cat:'phy'},{name:'Rock Slide',type:'Rock',cat:'phy'},
  {name:'Rock Smash',type:'Fighting',cat:'phy'},{name:'Rock Throw',type:'Rock',cat:'phy'},{name:'Rock Tomb',type:'Rock',cat:'phy'},
  {name:'Rollout',type:'Rock',cat:'phy'},{name:'Safeguard',type:'Normal',cat:'sta'},{name:'Sand Attack',type:'Ground',cat:'sta'},
  {name:'Sandstorm',type:'Rock',cat:'sta'},{name:'Secret Power',type:'Normal',cat:'phy'},{name:'Seismic Toss',type:'Fighting',cat:'phy'},
  {name:'Shadow Ball',type:'Ghost',cat:'phy'},{name:'Signal Beam',type:'Bug',cat:'spe'},{name:'Silver Wind',type:'Bug',cat:'spe'},
  {name:'Sing',type:'Normal',cat:'sta'},{name:'Sky Attack',type:'Flying',cat:'phy'},{name:'Slash',type:'Normal',cat:'phy'},
  {name:'Sleep Powder',type:'Grass',cat:'sta'},{name:'Sludge',type:'Poison',cat:'spe'},{name:'Sludge Bomb',type:'Poison',cat:'spe'},
  {name:'Smog',type:'Poison',cat:'spe'},{name:'Smokescreen',type:'Normal',cat:'sta'},{name:'Solar Beam',type:'Grass',cat:'spe'},
  {name:'Spark',type:'Electric',cat:'spe'},{name:'Spider Web',type:'Bug',cat:'sta'},{name:'Spite',type:'Ghost',cat:'sta'},
  {name:'Steel Wing',type:'Steel',cat:'phy'},{name:'Stomp',type:'Normal',cat:'phy'},{name:'Strength',type:'Normal',cat:'phy'},
  {name:'String Shot',type:'Bug',cat:'sta'},{name:'Stun Spore',type:'Grass',cat:'sta'},{name:'Submission',type:'Fighting',cat:'phy'},
  {name:'Substitute',type:'Normal',cat:'sta'},{name:'Sunny Day',type:'Fire',cat:'sta'},{name:'Surf',type:'Water',cat:'spe'},
  {name:'Sweet Scent',type:'Normal',cat:'sta'},{name:'Swords Dance',type:'Normal',cat:'sta'},{name:'Tackle',type:'Normal',cat:'phy'},
  {name:'Tail Whip',type:'Normal',cat:'sta'},{name:'Taunt',type:'Dark',cat:'sta'},{name:'Thief',type:'Dark',cat:'phy'},
  {name:'Thunder',type:'Electric',cat:'spe'},{name:'Thunder Wave',type:'Electric',cat:'sta'},{name:'Thunderbolt',type:'Electric',cat:'spe'},
  {name:'Thunder Shock',type:'Electric',cat:'spe'},{name:'Torment',type:'Dark',cat:'sta'},{name:'Toxic',type:'Poison',cat:'sta'},
  {name:'Twister',type:'Dragon',cat:'spe'},{name:'Twineedle',type:'Bug',cat:'phy'},{name:'Vine Whip',type:'Grass',cat:'spe'},
  {name:'Vital Throw',type:'Fighting',cat:'phy'},{name:'Water Gun',type:'Water',cat:'spe'},{name:'Water Pulse',type:'Water',cat:'spe'},
  {name:'Waterfall',type:'Water',cat:'spe'},{name:'Whirlpool',type:'Water',cat:'spe'},{name:'Will-O-Wisp',type:'Fire',cat:'sta'},
  {name:'Wing Attack',type:'Flying',cat:'phy'},{name:'Withdraw',type:'Water',cat:'sta'},{name:'Wrap',type:'Normal',cat:'phy'},
  {name:'Yawn',type:'Normal',cat:'sta'},
];

// ═══════════════════════════════
// TMs & HMs — FRLG locations
// DO NOT alter — verified against FRLG via Serebii + Bulbapedia
// ═══════════════════════════════
const TM_HM=[
  {num:'TM01',move:'Focus Punch',type:'Fighting',cat:'phy',loc:'Silph Co. (Floor 5)'},
  {num:'TM02',move:'Dragon Claw',type:'Dragon',cat:'spe',loc:'Victory Road'},
  {num:'TM03',move:'Water Pulse',type:'Water',cat:'spe',loc:'Cerulean Gym — Misty reward'},
  {num:'TM04',move:'Calm Mind',type:'Psychic',cat:'sta',loc:'Saffron Gym — Sabrina reward'},
  {num:'TM05',move:'Roar',type:'Normal',cat:'sta',loc:'Route 4 / Celadon Dept. Store (₽1000)'},
  {num:'TM06',move:'Toxic',type:'Poison',cat:'sta',loc:'Fuchsia Gym — Koga reward'},
  {num:'TM07',move:'Hail',type:'Ice',cat:'sta',loc:'Victory Road'},
  {num:'TM08',move:'Bulk Up',type:'Fighting',cat:'sta',loc:'Silph Co. (Floor 7)'},
  {num:'TM09',move:'Bullet Seed',type:'Grass',cat:'spe',loc:'Mt. Moon (entrance)'},
  {num:'TM10',move:'Hidden Power',type:'Normal',cat:'spe',loc:'Pickup ability (5% chance)'},
  {num:'TM11',move:'Sunny Day',type:'Fire',cat:'sta',loc:'Safari Zone'},
  {num:'TM12',move:'Taunt',type:'Dark',cat:'sta',loc:'Team Rocket Hideout (B2)'},
  {num:'TM13',move:'Ice Beam',type:'Ice',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM14',move:'Blizzard',type:'Ice',cat:'spe',loc:'Pokémon Mansion'},
  {num:'TM15',move:'Hyper Beam',type:'Normal',cat:'phy',loc:'Celadon Dept. Store (₽7500)'},
  {num:'TM16',move:'Light Screen',type:'Psychic',cat:'sta',loc:'Celadon Dept. Store (roof, ₽3000)'},
  {num:'TM17',move:'Protect',type:'Normal',cat:'sta',loc:'Kanto Power Plant'},
  {num:'TM18',move:'Rain Dance',type:'Water',cat:'sta',loc:'Route 15'},
  {num:'TM19',move:'Giga Drain',type:'Grass',cat:'spe',loc:'Celadon Gym — Erika reward'},
  {num:'TM20',move:'Safeguard',type:'Normal',cat:'sta',loc:'Celadon Dept. Store (roof, ₽3000)'},
  {num:'TM21',move:'Frustration',type:'Normal',cat:'phy',loc:'Team Rocket Hideout (B3)'},
  {num:'TM22',move:'Solar Beam',type:'Grass',cat:'spe',loc:'Pokémon Mansion'},
  {num:'TM23',move:'Iron Tail',type:'Steel',cat:'phy',loc:'Celadon Game Corner (3500 coins)'},
  {num:'TM24',move:'Thunderbolt',type:'Electric',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM25',move:'Thunder',type:'Electric',cat:'spe',loc:'Kanto Power Plant'},
  {num:'TM26',move:'Earthquake',type:'Ground',cat:'phy',loc:'Viridian Gym — Giovanni reward'},
  {num:'TM27',move:'Return',type:'Normal',cat:'phy',loc:'Route 12'},
  {num:'TM28',move:'Dig',type:'Ground',cat:'phy',loc:'Cerulean City NPC / Celadon Dept. Store'},
  {num:'TM29',move:'Psychic',type:'Psychic',cat:'spe',loc:'Saffron City (Mr. Psychic\'s house) / Game Corner (3500 coins)'},
  {num:'TM30',move:'Shadow Ball',type:'Ghost',cat:'phy',loc:'Celadon Game Corner (4500 coins)'},
  {num:'TM31',move:'Brick Break',type:'Fighting',cat:'phy',loc:'S.S. Anne / Celadon Dept. Store'},
  {num:'TM32',move:'Double Team',type:'Normal',cat:'sta',loc:'Safari Zone'},
  {num:'TM33',move:'Reflect',type:'Psychic',cat:'sta',loc:'S.S. Anne (B1) / Celadon Dept. Store'},
  {num:'TM34',move:'Shock Wave',type:'Electric',cat:'spe',loc:'Vermilion Gym — Lt. Surge reward'},
  {num:'TM35',move:'Flamethrower',type:'Fire',cat:'spe',loc:'Celadon Game Corner (4000 coins)'},
  {num:'TM36',move:'Sludge Bomb',type:'Poison',cat:'spe',loc:'Team Rocket HQ (Island 5)'},
  {num:'TM37',move:'Sandstorm',type:'Rock',cat:'sta',loc:'Victory Road'},
  {num:'TM38',move:'Fire Blast',type:'Fire',cat:'spe',loc:'Cinnabar Gym — Blaine reward / Silph Co. (Floor 7)'},
  {num:'TM39',move:'Rock Tomb',type:'Rock',cat:'phy',loc:'Pewter Gym — Brock reward / Silph Co. (Floor 4)'},
  {num:'TM40',move:'Aerial Ace',type:'Flying',cat:'phy',loc:'Route 9'},
  {num:'TM41',move:'Torment',type:'Dark',cat:'sta',loc:'Silph Co. (Floor 4)'},
  {num:'TM42',move:'Facade',type:'Normal',cat:'phy',loc:'Rock Altar (Island 6)'},
  {num:'TM43',move:'Secret Power',type:'Normal',cat:'phy',loc:'Route 24 / Celadon Dept. Store'},
  {num:'TM44',move:'Rest',type:'Psychic',cat:'sta',loc:'Route 9'},
  {num:'TM45',move:'Attract',type:'Normal',cat:'sta',loc:'Route 24 / Celadon Dept. Store'},
  {num:'TM46',move:'Thief',type:'Dark',cat:'phy',loc:'Mt. Moon (B2)'},
  {num:'TM47',move:'Steel Wing',type:'Steel',cat:'phy',loc:'Safari Zone'},
  {num:'TM48',move:'Skill Swap',type:'Psychic',cat:'sta',loc:'Route 12'},
  {num:'TM49',move:'Snatch',type:'Dark',cat:'sta',loc:'Team Rocket Hideout (B4)'},
  {num:'TM50',move:'Overheat',type:'Fire',cat:'spe',loc:'Victory Road'},
  {num:'HM01',move:'Cut',type:'Normal',cat:'phy',loc:'S.S. Anne — Captain gift'},
  {num:'HM02',move:'Fly',type:'Flying',cat:'phy',loc:'Route 16'},
  {num:'HM03',move:'Surf',type:'Water',cat:'spe',loc:'Safari Zone (Secret House)'},
  {num:'HM04',move:'Strength',type:'Normal',cat:'phy',loc:'Safari Zone Warden (return Gold Teeth)'},
  {num:'HM05',move:'Flash',type:'Normal',cat:'sta',loc:'Route 2 (Oak\'s Aide, after 10 Pokémon caught)'},
  {num:'HM06',move:'Rock Smash',type:'Fighting',cat:'phy',loc:'Island 1 (Ember Spa)'},
  {num:'HM07',move:'Waterfall',type:'Water',cat:'spe',loc:'Island 4 (Icefall Cave)'},
];
